services:
  mysqldb:
    ports:
      - "3301:3306"
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: auto_commit
  autocommit:
    depends_on:
      - mysqldb
    build: .
    image: autocommit:0.0.1
    ports:
      - "8084:10005"