services:
  mysqldb:
    ports:
      - "3301:3306"
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
  autocommit:
    image: autocommit:0.0.1
    depends_on:
      mysqldb:
        condition: service_healthy
    volumes:
      - ./src:/app/src
    ports:
      - "8084:10005"
    shm_size: '2gb'
#    env_file:
#      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      PROGRAMMERS_ID: ${PROGRAMMERS_ID}
      PROGRAMMERS_PASSWORD: ${PROGRAMMERS_PASSWORD}
      GIT_USERNAME: ${GIT_USERNAME}
      GIT_EMAIL: ${GIT_EMAIL}
      GIT_ACCESS_TOKEN: ${GIT_ACCESS_TOKEN}
      GIT_REPO_URI: ${GIT_REPO_URI}


