services:
  mysqldb:
    ports:
      - "3301:3306"
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: auto_commit
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
  autocommit:
    depends_on:
      - mysqldb
    image: autocommit:0.0.1
    volumes:
      - ./src:/app/src
    ports:
      - "8084:10005"
    shm_size: '2gb'