services:
  mysqldb:
    ports:
      - "3301:3306"
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=auto_commit
      - MYSQL_USER=root

  autocommit:
    depends_on:
      - mysqldb
    image: autocommit:latest
    ports:
      - "8084:10005"